---

# Docker compose for example for the Coraza WAF
# This example assumes Docker is running in swarm mode
# Traefik will be used as the front end server accepting inbound connections and terminating SSL.
# The Coraza WAF will be used to protect the backend "whoami" service.

version: '3.8'

services:

  ## The "whoami" container
  ## This is the container that the WAF will be protecting
  whoami:
    image: traefik/whoami
    networks:
      - whoami

  ## Coraza WAF running on Caddy
  caddy:
    image: gbe0/coraza:latest
    depends_on:
      - whoami
    networks:
      - whoami
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REVERSE_PROXY=whoami:80

## Networks used by the above services
networks:
  ## Basic network used for the containers
  whoami: